env.data: dev

apiKey: ${secret_apiKey}

base-url: ${base_url}

client-id:
  kakao: ${kakao_client_id}
  naver: ${naver_client_id}
  google: ${google_client_id}

client-secret:
  kakao: ${kakao_client_secret}
  naver: ${naver_client_secret}
  google: ${google_client_secret}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${mysql_url}
    username: ${mysql_username}
    password: ${mysql_password}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false